sudo: false

language: go

env:
    global: 
        - GO111MODULE=on

go:
  - 1.11.x
  - 1.12.x

install: false
script:
- go test ./... -v -mod=vendor -race -count=1 -coverprofile=coverage.txt -covermode=atomic -timeout=5s

after_success:
  - bash <(curl -s https://codecov.io/bash)
