version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    volumes:
      - zookeeper:/opt/zookeeper-3.4.6/data
    networks:
      - commander
  kafka:
    image: wurstmeister/kafka:1.1.0
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    links:
      - zookeeper
    volumes:
      - kafka:/kafka
    networks:
      - commander
  postgres:
    image: postgres:9.5.3
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - commander
networks:
  commander:
    external: true
volumes:
  zookeeper:
  kafka:
  postgres:
