name: Go
on: [push]
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Go 1.11
      uses: actions/setup-go@v1
      with:
        go-version: 1.11
      id: go
      run: go test ./... -v -mod=vendor -race -count=1 -coverprofile=coverage.txt -covermode=atomic -timeout=120s

    - name: Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
      run: go test ./... -v -mod=vendor -race -count=1 -coverprofile=coverage.txt -covermode=atomic -timeout=120s

    - name: Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      run: go test ./... -v -mod=vendor -race -count=1 -coverprofile=coverage.txt -covermode=atomic -timeout=120s
      
